=== Lelouch72/Cours-Master/Documents/xml/Outils-pour-les-TP/exemple/cars.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT cars (car*)>
<!ELEMENT car (model, year, price, country?)>
<!ATTLIST car make NMTOKEN #REQUIRED>

<!ELEMENT model (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ATTLIST price currency (Euros|Livres|USD) #REQUIRED>
<!ELEMENT country (#PCDATA)>

=== Lelouch72/Cours-Master/Documents/xml/Outils-pour-les-TP/exemple/cars.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="cars.xsl"?>
<!--output="cars.html"-->
<!--xpath="//model"-->

<!DOCTYPE cars SYSTEM "cars.dtd">
<cars>
	<car make="BMW">
		<model>Z4 Roadster</model>
		<year>2012</year>
		<price currency="Euros">47500</price>
		<country>Germany</country>
	</car>
	<car make="Peugeot">
		<model>308 SW Style</model>
		<year>2012</year>
		<price currency="Euros">17790</price>
	</car>
	<car make="Peugeot">
		<model>RCZ Coup√©</model>
		<year>2013</year>
		<price currency="Euros">29900</price>
	</car>
</cars>
